import {
  DEV_BASE,
  DEV_BASE_VIEWS,
  DEV_CATEGORY_FIELDS,
  DEV_SENIORITY_FIELDS,
  DEV_SKILL_FIELDS,
  DEV_USER_FIELDS,
} from './airtable.dev';
import {
  PROD_BASE,
  PROD_BASE_VIEWS,
  PROD_CATEGORY_FIELDS,
  PROD_SENIORITY_FIELDS,
  PROD_SKILL_FIELDS,
  PROD_USER_FIELDS,
} from './airtable.prod';

export const AIRTABLE_FIELDS = {
  BASE: process.env.FUNCTIONS_EMULATOR === 'true' ? DEV_BASE : PROD_BASE,
  BASE_VIEWS: process.env.FUNCTIONS_EMULATOR === 'true' ? DEV_BASE_VIEWS : PROD_BASE_VIEWS,
  CATEGORY_FIELDS: process.env.FUNCTIONS_EMULATOR === 'true' ? DEV_CATEGORY_FIELDS : PROD_CATEGORY_FIELDS,
  SENIORITY_FIELDS: process.env.FUNCTIONS_EMULATOR === 'true' ? DEV_SENIORITY_FIELDS : PROD_SENIORITY_FIELDS,
  SKILL_FIELDS: process.env.FUNCTIONS_EMULATOR === 'true' ? DEV_SKILL_FIELDS : PROD_SKILL_FIELDS,
  USER_FIELDS: process.env.FUNCTIONS_EMULATOR === 'true' ? DEV_USER_FIELDS : PROD_USER_FIELDS,
};
