export enum SECRET_KEYS {
  AIRTABLE_API_KEY = 'AIRTABLE_API_KEY',
  AIRTABLE_BASE = 'AIRTABLE_BASE',
  CONTENTFUL_TOKEN = 'CONTENTFUL_MANAGEMENT_TOKEN',
  WEBAPP_URL = 'WEBAPP_URL',
  WEBAPP_DEV_URL = 'WEBAPP_DEV_URL',
}

export const AIRTABLE_SECRET_KEYS = [SECRET_KEYS.AIRTABLE_API_KEY, SECRET_KEYS.AIRTABLE_BASE];
export const URL_SECRET_KEYS = [SECRET_KEYS.WEBAPP_URL, SECRET_KEYS.WEBAPP_DEV_URL];
export const CONTENTFUL_SECRET_KEYS = [SECRET_KEYS.CONTENTFUL_TOKEN];
