export enum SECRET_KEYS {
  AIRTABLE_API_KEY = 'AIRTABLE_API_KEY',
  AIRTABLE_BASE = 'AIRTABLE_BASE',
  CONTENTFUL_TOKEN = 'CONTENTFUL_MANAGEMENT_TOKEN',
  WEBAPP_URL = 'WEBAPP_URL',
  WEBAPP_DEV_URL = 'WEBAPP_DEV_URL',
  SLACK_MAINTAINER_ID = 'SLACK_MAINTAINER_ID',
  SLACK_TOKEN = 'SLACK_TOKEN',
  SLACK_REMINDER_CHANNEL_ID = 'SLACK_REMINDER_CHANNEL_ID',
  CONTENTFUL_SPACE_ID = 'CONTENTFUL_SPACE_ID',
  CONTENTFUL_ENVIRONMENT = 'CONTENTFUL_ENVIRONMENT',
}

export const AIRTABLE_SECRET_KEYS = [SECRET_KEYS.AIRTABLE_API_KEY, SECRET_KEYS.AIRTABLE_BASE];
export const URL_SECRET_KEYS = [SECRET_KEYS.WEBAPP_URL, SECRET_KEYS.WEBAPP_DEV_URL];
export const CONTENTFUL_SECRET_KEYS = [
  SECRET_KEYS.CONTENTFUL_TOKEN,
  SECRET_KEYS.CONTENTFUL_SPACE_ID,
  SECRET_KEYS.CONTENTFUL_ENVIRONMENT,
];
export const SLACK_SECRET_KEYS = [
  SECRET_KEYS.SLACK_MAINTAINER_ID,
  SECRET_KEYS.SLACK_TOKEN,
  SECRET_KEYS.SLACK_REMINDER_CHANNEL_ID,
];
